---
kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: mohemohe/mastodon
      auto_tag: true
      auto_tag_suffix: plusminus
      username: mohemohe
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - mstdn.plusminus.io
